wrapperVersion=3.3.4
distributionType=only-script
distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.15/apache-maven-3.9.15-bin.zip
distributionSha256Sum=B0D9292F06C5FADED31DDCB6CB69099F316D6FEA40A7778624B259BAD9FED18A