name: Publish Release with Artifacts
# The action must be manually triggered and provided with the version number
# It will run tests with maven, build and sign artifacts and deploy them to maven central.
# A new GitHub release will be created and all the artifacts attached.

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (X.Y.Z format, e.g. 1.0.0)'
        required: true
        type: string

# permissions required to write to the GitHub release
permissions:
  contents: write

env:
  VERSION: ${{ inputs.version }}
  TAG: v${{ inputs.version }}
  MAVEN_ARGS: "--batch-mode --fail-at-end"

jobs:
  test:
    name: Run all Tests
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6
      - name: Setup JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup maven
        run: |
          chmod +x ./mvnw
          ./mvnw clean

      - name: Set version
        run: ./mvnw versions:set -DnewVersion=${{ env.VERSION }}

      - name: Run Maven verify phase
        run: ./mvnw clean test

  publish:
    name: Build, Sign and publish artifacts
    runs-on: ubuntu-slim
    environment: Maven central
    needs: [test]
    steps:
      - uses: actions/checkout@v6
      - name: Setup JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: 'central'
          server-username: 'SONATYPE_USER_TOKEN_USERNAME'
          server-password: 'SONATYPE_USER_TOKEN_PASSWORD'
          gpg-private-key: ${{ secrets.OPEN_PGP_PRIVATE_KEY }}
          gpg-passphrase: 'PRIVATE_KEY_PASSPHRASE'

      - name: Setup maven
        run: |
          chmod +x ./mvnw
          ./mvnw clean

      - name: Set version
        run: ./mvnw versions:set -DnewVersion=${{ env.VERSION }}

      - name: Run Maven package phase
        run: ./mvnw -P release deploy -DskipTests
        env:
          SONATYPE_USER_TOKEN_USERNAME: ${{ secrets.SONATYPE_USER_TOKEN_USERNAME }}
          SONATYPE_USER_TOKEN_PASSWORD: ${{ secrets.SONATYPE_USER_TOKEN_PASSWORD }}
          PRIVATE_KEY_PASSPHRASE: ${{ secrets.PRIVATE_KEY_PASSPHRASE }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: artifacts
          path: processor/target/spring-boot-configuration-docgen-processor-${{env.VERSION}}*
          if-no-files-found: error

  create-release:
    name: Create GitHub Release and Attach Artifacts
    runs-on: ubuntu-slim
    needs: [publish]
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-artifacts
          # Merges downloaded artifacts into the target path directly instead of creating subfolders per artifact name
          merge-multiple: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ env.TAG }}
          name: ${{ env.TAG }}
          draft: false
          # attach all files from the directory
          files: release-artifacts/*
          fail_on_unmatched_files: true